Single Dimensional Array

In [1]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [3]:
type(n1)

numpy.ndarray

Multi Dimensional Array

In [2]:
import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [4]:
type(n2)

numpy.ndarray

INITIALIZING NUMPY ARRAY

1) WITH ZEROES

In [9]:
import numpy as np
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [10]:
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2) SAME NUMBERS

In [12]:
n5=np.full((3,4),13)
n5

array([[13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13]])

In [15]:
n6=np.full((6,6),6)
n6

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

3) RANGE

In [16]:
import numpy as np
n7=np.arange(15,26)
n7

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [17]:
n8=np.arange(23,100,11)
n8

array([23, 34, 45, 56, 67, 78, 89])

In [20]:
n9=np.arange(23)
n9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

4) random no.

In [21]:
n10=np.random.randint(1,200,10)
n10

array([134, 110, 166, 111, 106, 110, 199, 115, 131,  82])

In [25]:
n11=np.random.randint(2,100,7)
n11

array([77, 25, 67,  7, 20, 12, 14])

NUMPY- SHAPE

In [27]:
import numpy as np
n12=np.array([[10,20,25,30],[20,30,50,45]])
n12

array([[10, 20, 25, 30],
       [20, 30, 50, 45]])

In [28]:
n12.shape

(2, 4)

In [32]:
n12.shape=(4,2)

In [33]:
n12

array([[10, 20],
       [25, 30],
       [20, 30],
       [50, 45]])

Joining NumPy arrays

In [37]:
import numpy as np
n13=np.array([13,23,33])
n14=np.array([100,200,300])
np.vstack((n13,n14))

array([[ 13,  23,  33],
       [100, 200, 300]])

In [38]:
np.hstack((n13,n14))

array([ 13,  23,  33, 100, 200, 300])

In [39]:
np.column_stack((n13,n14))

array([[ 13, 100],
       [ 23, 200],
       [ 33, 300]])

In [43]:
np.column_stack((n14,n13))

array([[100,  13],
       [200,  23],
       [300,  33]])

In [47]:
n15=np.array([4,44,444])
np.hstack((n13,n14,n15))

array([ 13,  23,  33, 100, 200, 300,   4,  44, 444])

NumPy intersection and difference

In [3]:
import numpy as np
n16=np.array([10,20,30,40,50,60])
n17=np.array([50,60,70,80,90])
np.intersect1d(n16,n17)

array([50, 60])

In [5]:
np.setdiff1d(n16,n17)

array([10, 20, 30, 40])

In [6]:
np.setdiff1d(n17,n16)

array([70, 80, 90])

NumPy array mathematics

In [9]:
n18=np.array([13,23])
n19=np.array([33,43])
np.sum([n18,n19])

112

In [11]:
np.sum([n18,n19],axis=0)

array([46, 66])

In [12]:
np.sum([n18,n19],axis=1)

array([36, 76])

In [14]:
n20=np.array([10,20,30,40])
n20=n20+1
n20

array([11, 21, 31, 41])

In [16]:
n20-1

array([ 9, 19, 29, 39])

In [17]:
n20*2

array([20, 40, 60, 80])

In [18]:
n20/2

array([ 5., 10., 15., 20.])

In [20]:
n21=np.array([10,20,30,40,50,60])
np.mean(n21)

35.0

In [23]:
n22=np.array([11,44,5,96,67,85])
np.median(n22)

55.5

In [24]:
np.std(n22)

34.644223504391356

In [26]:
import numpy as np
n23=np.array([10,20,30,40,50,60])
np.save('my_numpy',n23)

In [27]:
np.load('my_numpy.npy')

array([10, 20, 30, 40, 50, 60])

In [28]:
print(np.__version__)


1.18.5


Array Indexing

In [29]:
import numpy as np
n24=np.array([2,4,5,9,5,7])
print(n24[2]+n24[4])

10


In [31]:
import numpy as np
n25=np.array([[10,20,30,40],[50,60,70,80]])
print('3rd element of 2nd array is:',n25[1,2])

3rd element of 2nd array is: 70


In [32]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [33]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [35]:
print(arr[4:])

[5 6 7]


In [36]:
print(arr[:4])


[1 2 3 4]


In [37]:
print(arr[-3:-1])

[5 6]


In [38]:
print(arr[1:5:2])

[2 4]


In [39]:
print(arr[::2])

[1 3 5 7]


In [41]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr1[1,:3])

[5 6 7]


In [42]:
print(arr1[0:2, 2])

[3 7]


In [45]:
print(arr1[:,1:4])

[[2 3 4]
 [6 7 8]]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [48]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [49]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [51]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [52]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [53]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [54]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [55]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.transpose(arr3)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr4=np.array([[9,8,7],[6,5,4],[3,2,1]])
arr4

PANDAS

In [1]:
import pandas as pd

In [5]:
l1=[1,2,3,4,5]

In [10]:
s1=pd.Series(l1)

In [7]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
type(s1)

pandas.core.series.Series

In [12]:
import pandas as pd
s2=pd.Series([1,2,3,4,5],index=['sparta','poo','nik','d','e'])
s2

sparta    1
poo       2
nik       3
d         4
e         5
dtype: int64

In [14]:

s3=pd.Series({'a':100,'b':200,'c':300})
s3

a    100
b    200
c    300
dtype: int64

In [15]:
s4=pd.Series({'a':100,'b':200,'c':300},index=['b','d','c','a'])
s4

b    200.0
d      NaN
c    300.0
a    100.0
dtype: float64

In [16]:
s5=pd.Series([1,2,3,4,5,6,7,8,9])
s5[3]

4

In [17]:
s5[-3:]

6    7
7    8
8    9
dtype: int64

In [18]:
s5[-3:0]

Series([], dtype: int64)

In [19]:
s5[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [20]:
s5[4:2]

Series([], dtype: int64)

In [21]:
s5+10

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [22]:
s5-100

0   -99
1   -98
2   -97
3   -96
4   -95
5   -94
6   -93
7   -92
8   -91
dtype: int64

In [25]:
s5*2

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [27]:
s6=pd.Series([10,20,30,40,50,60,70,80,90])
s6

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [28]:
s5+s6

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [33]:
d1=pd.DataFrame({"name":['Jacob','Eric','Kevin','Nik'],"Marks":[70,80,90,100]})
d1

name  Marks
0  Jacob     70
1   Eric     80
2  Kevin     90
3    Nik    100

In [36]:
iris=pd.read_csv('iris.csv')

In [37]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [38]:
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [40]:
iris.shape

(150, 6)

In [42]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [44]:
iris.iloc[0:4,0:5]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2

In [48]:
iris.loc[5:11,("SepalLengthCm","SepalWidthCm")]

SepalLengthCm  SepalWidthCm
5             5.4           3.9
6             4.6           3.4
7             5.0           3.4
8             4.4           2.9
9             4.9           3.1
10            5.4           3.7
11            4.8           3.4

In [51]:
iris.drop('SepalLengthCm',axis=1)

Id  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1           3.5            1.4           0.2     Iris-setosa
1      2           3.0            1.4           0.2     Iris-setosa
2      3           3.2            1.3           0.2     Iris-setosa
3      4           3.1            1.5           0.2     Iris-setosa
4      5           3.6            1.4           0.2     Iris-setosa
..   ...           ...            ...           ...             ...
145  146           3.0            5.2           2.3  Iris-virginica
146  147           2.5            5.0           1.9  Iris-virginica
147  148           3.0            5.2           2.0  Iris-virginica
148  149           3.4            5.4           2.3  Iris-virginica
149  150           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [52]:
iris.drop([1,2,3],axis=0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
6       Iris-setosa  
7       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[147 rows x 6 columns]

In [53]:
iris.drop(1,axis=0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[149 rows x 6 columns]

In [54]:
iris.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [55]:
iris.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [56]:
iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [57]:
iris.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [59]:
def half(s):
    s*0.5

In [60]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [64]:
def half(s):
    return s*0.5
iris[['SepalLengthCm','SepalWidthCm']].apply(half)

SepalLengthCm  SepalWidthCm
0             2.55          1.75
1             2.45          1.50
2             2.35          1.60
3             2.30          1.55
4             2.50          1.80
..             ...           ...
145           3.35          1.50
146           3.15          1.25
147           3.25          1.50
148           3.10          1.70
149           2.95          1.50

[150 rows x 2 columns]

In [65]:
iris['Species'].value_counts()

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: Species, dtype: int64

In [68]:
iris.sort_values(by='SepalLengthCm')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
42    43            4.4           3.2            1.3           0.2   
38    39            4.4           3.0            1.3           0.2   
8      9            4.4           2.9            1.4           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   
117  118            7.7           3.8            6.7           2.2   
135  136            7.7           3.0            6.1           2.3   
131  132            7.9           3.8            6.4           2.0   

            Species  
13      Iris-setosa  
42      Iris-setosa  
38      Iris-setosa  
8       Iris-setosa  
41      Iris-setosa  
..              ...  
122  Iris-virginica  
118  Iris-virginica  
117  Iris-virginica  
135  Iris-virginica  
131  Iris-virginica  

[150 rows x 6 columns]

In [69]:
a_=13
print(a_)

13
